######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 9 10:46:24 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h \
    setdesktop.h \
    setdesktop.h
SOURCES += main.cpp mainwindow.cpp \
    setdesktop.cpp

FORMS += \
    setdesktop.ui
