######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 28 10:01:30 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    xwindowfinder.cpp

HEADERS += \
    xwindowfinder.h
