######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 26 11:39:28 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += button.h calculator.h
SOURCES += button.cpp calculator.cpp main.cpp
