######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 7 08:33:47 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += border.h frame.h header.h \
    defs.h
SOURCES += border.cpp frame.cpp header.cpp main.cpp
